apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-ingress-dr
  namespace: default
spec:
  host: helloworld-00001.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE