apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  traffic:
#    - tag: current
#      revisionName: example-service-1
#      percent: 100
    - tag: latest
      latestRevision: true
      percent: 100
  template:
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
          - name: TARGET
            value: "Go Sample v1"
