apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
          - name: TARGET
            value: "Go Sample v1"
