apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: helloworld-dm.default.172.17.0.100.sslip.io
spec:
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFwTVJVd0V3WURWUVFLREF4RmVHRnQKY0d4bElFbHVZeTR4RURBT0JnTlZCQU1NQjBWNFlXMXdiR1V3SGhjTk1qTXdNVEU0TURnMU5EUTFXaGNOTWpRdwpNVEU0TURnMU5EUTFXakFwTVJVd0V3WURWUVFLREF4RmVHRnRjR3hsSUVsdVl5NHhFREFPQmdOVkJBTU1CMFY0CllXMXdiR1V3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRERVYnFIWTgvTVZnWDcKYUY5WmxMZGpWOS9TZlljTFRSNytMTzBpTWJuSXF5ODNmM0hwcVR6V1NDRGlCYURobXQ5a21WMzJkeXQ4QmZIawpoaEFpQlFTRTdzbnh0WHZmTUxKVG9tVHA0SUZRUGRjZHdhUnAxNVBOUDJ6U2xHaGVHVlcwOElVQUU0U2NZTk9pCkY2eGJjR05RK3Z4M2ZOd2hwYUVSWkJnbHpuc1VUcjlLVEhBV2pYVTJlaWluTzFKNy9FbHh0RXBLQU5RQUpwMS8KSDlKazZ1dThVT2t1c1Q1cWtlK29nblBWOXZxdTNOczIxNCtobFdaS2JscTNCWFQxcFk5dmtZM1NZWDdpaStlTwpxSGtjZU9kei85S1FBSWlvTTl3L1NCbE5TWEhKTmxaVnRzWVJqMHRYNHlGNUNGeDhSakxuK1ZUMGdTWG03NDdaCkd0OUpxbGo1QWdNQkFBR2pIREFhTUJnR0ExVWRFUVFSTUErQ0RTb3VaWGhoYlhCc1pTNWpiMjB3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFLR1VCYVh4TkhvU0o1V3RFMWV4MUYzMElZVEhMbUUxSng5ZEEzbmcreURKSStNagpXU25zUzBodnA1eGFQV1VKWGxSOUtUWDk0d3F6TjY0UGJlTVJpajh0aDlqQmJBMS9pYkEvcmlzTVJ5bXc0RWRBCkJiSENNRWVydk5PWFRDeTREaVlrYjM3N3dCd3VOdm93azdKSGRidFZDenRkeDVvd1dJcjZ5UFdwdFo5UHJZTFMKM0gvdkVGRE5UbVlZZHNTSjVSOTdvaTNGS1pIZzhDR2FNTGJJSXQ4b2JoZnNtd2pDazFEYk5Fb0hxT09LSVJNRQo0STFoN014emQrRG9SUWs2WG5pWWNmM29tT3pIeG5GR09pVHJxMSt5VlJBaTVqOTJ0TzR5eU4rRXQ2UFhUb3VXCkJOUGhabXVIWkJ5VG03WnEwK0VsVDFEWGQ3a0x0QmlaSG1qVmpmaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRERVYnFIWTgvTVZnWDcKYUY5WmxMZGpWOS9TZlljTFRSNytMTzBpTWJuSXF5ODNmM0hwcVR6V1NDRGlCYURobXQ5a21WMzJkeXQ4QmZIawpoaEFpQlFTRTdzbnh0WHZmTUxKVG9tVHA0SUZRUGRjZHdhUnAxNVBOUDJ6U2xHaGVHVlcwOElVQUU0U2NZTk9pCkY2eGJjR05RK3Z4M2ZOd2hwYUVSWkJnbHpuc1VUcjlLVEhBV2pYVTJlaWluTzFKNy9FbHh0RXBLQU5RQUpwMS8KSDlKazZ1dThVT2t1c1Q1cWtlK29nblBWOXZxdTNOczIxNCtobFdaS2JscTNCWFQxcFk5dmtZM1NZWDdpaStlTwpxSGtjZU9kei85S1FBSWlvTTl3L1NCbE5TWEhKTmxaVnRzWVJqMHRYNHlGNUNGeDhSakxuK1ZUMGdTWG03NDdaCkd0OUpxbGo1QWdNQkFBRUNnZ0VBTUxnREdlQklwY1JUUzZsMkZ5Y2tNekJwRU56a3dXbmtNQ3hPbmZmZlNuR0EKbm93NGdyc0hCTUFMQzdXeHNuUnFBbkxLNEQ1TFoyMG9NQU5NcE4reGgrTDBGa2xaYzR0Mi82dURGbDg4Z2lKYQp0UDVuSDB0NWYzbXhrRGthYTFaUWJZaU05RDdxRmdPRTVtcVhRRnVoT2tMUWxKRmRhenNnR1BGcG9JeUhZTUh2CnpkT0VGb016elpJQzNubFFlNHVnTGhlbVd4YXhPTVA2TWZjdnhRLzhwa3hLLzM2WnpzcjZuY3VGaUExcmFYWk0KTi9VU1Q1VS9oYlRGTkhrMkIzRkhxYlI3NGVvOXY2TVNNS2xZMnBUZ2FqSzhrYVhhS2tybnJWODh5WDdEaEl2YQp1TWY1NjF0Y1NKSTIyYjFHMnYxaUVYTWNvaUdPL1VhYUt1WCtIZjdDTVFLQmdRRHhaRkUzd2ZnWk1JY1BEM2FuCmhsT3EvOWJkem5oUlhkTEdqQTY1UkJNV1IrL0k1V3hIV1IrMi9CQ3FlWDRyenVjRmtLdEJZb29DNmpHd3NFQlAKU05vYUxONVU1aTVKUkFBampkODd0L3owQldDNjdpRFJZOGFFdjFRaldoZ0xJTG10ZjVER0IzQjVTeDdYZUlQMQpjSmYzSXFxdk1XSTZFRUUzUHVHT0lCalZSUUtCZ1FEUEk2V1hLMHhVaW9oK00vNUFiS0QzSGtIRXM1UzRjNXdJCjJDUUJIZmNrdFE2L2VpYlViOW1tMVFpelRXeE55YzR3QVdQaFRYRjUrWHdYRE5MN3FlU0xWNGFzMFp0WEttMWIKSFRlSEYyQnpqR095T2JYUHlnWk1ERGxsZExvVm9HWis4MlFkSloyWXgrNkF1RllwNzBqYzd5WWQvNmtuUmJRcApNV1FSMFA3T0pRS0JnQ094M055czN4NENjZ1pGR0J1Zm5tR3I0VDc5V0FkWUkySGV0aEtwUVZWTEgrY0tIZC9UCkN3Q0k5NEh0NHoxaEpBSkxxVGRLOWZPR1pBQ25uMnJaNy81czRoZVZ6Z1JoZk0vRkc5eDkwWGJZRUx5emw4QysKeTAwMzZaNHNwVitINEUwS2p3THBlTFZHNlhHZFRZNE9yem9KTTBvaXVFNnp0cUVQdUZURzVFVXRBb0dBVzI4dgp6Qy9uckxYT0ZHOWMveEUwYUlEcHBTdGtMWnVTdC9DNHkrbHZTN3ZFZTg4dXpyMWt4UmpxazBOTTJIV0pWM1YxCm9tRnVBdHFXNVJIYkhBM2RmWWl3UVI3eFJDUE5TOWYweCtRUXhsQ2xQV251RUgvc0VhdWZ0bUkxTmhDc3pjTWcKWVNGV2xMZEVWM3VIUlZHRHgwcWxkNzUvNjM4QVRPS3BlcGZYc2lVQ2dZQUNTREQwRDYxMTB1b3N3dnVrcFRWbApTdTI2WDRoaDVxckVxWGdmbGtGclBVWWJ4STBOdmY1OEFtRk01UFZ5Rm5BanZCMTNmaTZXRDZIMWxWYzAzaGFwCndHK2ZPMWxEMFQyNmhjaXRhalM0OWRabWNKOE5iZkNSM3YvdnJjbndHNVRaUWV2dFp5QXhRa3R2eXhuZEJjTkgKa3F4ZlZ4aXNJWFNRZWEwblR6cUd1dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: tls-secret
  namespace: default
type: kubernetes.io/tls
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: helloworld-dm.default.172.17.0.100.sslip.io
  namespace: default
spec:
  ref:
    name: helloworld
    kind: Service
    apiVersion: serving.knative.dev/v1
  tls:
    secretName: tls-secret
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
          - name: TARGET
            value: "Go Sample v1"
