apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  annotations:
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
  labels:
    networking.knative.dev/visibility: cluster-local
  name: knative-serving-certs
  namespace: knative-serving
spec:
  dnsNames:
  - knative
  domain: knative
  secretName: knative-serving-certs
