apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-internal-ca
  namespace: cert-manager
spec:
  secretName: knative-internal-ca
  commonName: knative
  usages:
    - server auth
    - client auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
