apiVersion: v1
data:
  issuerRef: |
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  internalIssuerRef: |
    kind: ClusterIssuer
    name: knative-internal-encryption-issuer
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: net-certmanager
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.10.0
    networking.knative.dev/certificate-provider: cert-manager
  name: config-certmanager
  namespace: knative-serving
