apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
spec: 
  containers: 
    - image: busybox
      name: busybox
      command:
      - sleep
      - "36000"
      volumeMounts: 
        - mountPath: /etc/creds
          name: creds
          readOnly: true
  volumes: 
    - name: creds
      secret: 
        secretName: my-secret
