apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: routing-serving-certs
  namespace: knative-serving
spec:
  dnsNames:
    - kn-routing
    - data-plane.knative.dev # for reverse-compatibility with net-* implementations that do not work with multi-SANs
  secretName: routing-serving-certs
  issuerRef:
    name: knative-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io