---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: first
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
          - name: TARGET
            value: "from first"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: second
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
          - name: TARGET
            value: "from second"