apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  annotations:
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
  labels:
    networking.knative.dev/visibility: cluster-local
  name: my-cert
  namespace: demo
spec:
  dnsNames:
  - hello-example.default
  - hello-example.default.svc
  - hello-example.default.svc.cluster.local
  domain: hello-example.default.svc.cluster.local
  secretName: my-cert
